### ISSUE TITLE
How can i use DocSPA-library on Angular 7?

### ISSUE THREAD

**Issue by SerhiiYatsyn** [swimlane/DocSPA#17]
Following [this tutorial](https://swimlane.github.io/DocSPA/angular-cli-install) i installed library into my project and got such an error:
![image](https://user-images.githubusercontent.com/44030464/75986817-6739dd80-5ef7-11ea-80bd-b12f317613d6.png)
How to fix it?

**Comment by Hypercubed** [comment]
Hi @SerhiiYatsyn not specifically angular 7, you may need to update to ng8 or 9.

Specificly on your issues... you need to manually install peerDependecies.  You likely received a message erlier in the install listing peers that you will need to install.

**Comment by norbertbede** [comment]
@Hypercubed  we have 3 success-full documentation project based on default github project.

When we create a vanilla project based on documentation or trying put npm's to our project we lack on above issue reported by @SerhiiYatsyn  We are using angular 9.1.7

https://swimlane.github.io/DocSPA/angular-cli-install

_also we added as failover package.json from working project._ 
https://github.com/swimlane/DocSPA/blob/master/package.json

doesnt works. :( 
@Hypercubed  may I ask your help on this issue ? 

norbertbede

**Comment by Hypercubed** [comment]
Please try `npm i mdast@latest`
