### ISSUE TITLE
ID defined for header is not considered in generated menu

### ISSUE THREAD

**Issue by norbertbede** [swimlane/DocSPA#22]
**Related feature**
https://github.com/swimlane/DocSPA/blob/master/src/docs/features.md#ids

**Issue:** ID defined for header is not considered in generated menu
tested in right menu.the menu item is still generated instead use defined id.

**Comment by Hypercubed** [comment]
I'm sorry I dont understand this issue.  Please reopen if you can show me a reproduction og this issue.
