### ISSUE TITLE
Dynamic Content Module work in Safari

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/DocSPA#44]
A user reported an issue in the ngx-graph repo that the demo page doesn't render the SVGs in Safari. ngx-graph works on Safari, so we need to investigate whether this is a DocSPA issue.

https://github.com/swimlane/ngx-graph/issues/315

**Comment by Hypercubed** [comment]
Looks like the Dynamic Content Module doesn't work under safari: https://swimlane.github.io/DocSPA/modules/runtime

**Comment by Hypercubed** [comment]
Safari doesn't support extending built-in elements: https://github.com/WICG/webcomponents/issues/509#issuecomment-233419167

**Comment by Hypercubed** [comment]
TODO: update to use @ungap/custom-elements
