### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by DarthKurt** [swimlane/DocSPA#6]
I have created empty app according [guide](https://swimlane.github.io/DocSPA/angular-cli-install#adding-docspa-to-a-angular-cli-app).

When I try to build such app I have an errors related to the imports inside the library
```
ERROR in node_modules/@swimlane/docspa-core/lib/custom-components/embed-file.d.ts(5,8): error TS1192: Module '".../node_modules/@types/vfile/index"' has no default export.
node_modules/@swimlane/docspa-core/lib/custom-components/toc-pagination.component.d.ts(6,8): error TS1192: Module '".../node_modules/@types/vfile/index"' has no default export.
node_modules/@swimlane/docspa-core/lib/docspa-core.component.d.ts(3,8): error TS1192: Module '".../node_modules/@types/vfile/index"' has
no default export.
node_modules/@swimlane/docspa-core/lib/plugins/links.d.ts(2,10): error TS2305: Module '".../node_modules/@types/unist/index"' has no exported member 'UNIST'.
node_modules/@swimlane/docspa-core/lib/services/location.service.d.ts(1,8): error TS1192: Module '".../node_modules/@types/vfile/index"'
has no default export.
node_modules/@swimlane/docspa-core/lib/services/markdown.service.d.ts(6,8): error TS1192: Module '".../node_modules/@types/vfile/index"'
has no default export.
```

**Comment by Hypercubed** [comment]
Hi @DarthKurt , Thank you for trying DocSPA.  There are still a lot of changes going on... I hope to be more stable when I jump to v2.

Did you start using this repo or the quick-start repo?  Remark/Unified (the markdown parser we are using) is just starting to add types... I believe this is the issue you are seeing.  Installing the types should fix the issues:

```
npm i -D @types/vfile @types/mdast @types/unist
```

You may also need to uninstall the previous types:

```
npm uninstall @paperist/types-remark
```

Please let us know if that works.
