### ISSUE TITLE
Angular v12 Release

### ISSUE THREAD

**Issue by temush** [swimlane/DocSPA#74]
Hello,

I would like to use ngx-graph in my project, but first the ngx-graph needs to be update to Angular v12 (https://github.com/swimlane/ngx-graph/issues/405). It has a dependency to DocSPA, which seems to be already on v12, but it's not released yet.

Can you please create a new DocSPA release supporting Angular v12?

**Comment by martypitt** [comment]
We're also waiting on ngx-graph releasing an Angular 12 version.  Is there anythign we can do on this project to help get the release across the line?
