### ISSUE TITLE
full aot support?

### ISSUE THREAD

**Issue by kostenickj** [swimlane/DocSPA#8]
Love this package, any chance on full AOT support? I get a ton of console errors trying to use AOT with this.

**Comment by Hypercubed** [comment]
Are you using the `RuntimeContentModule`?  As it is right now this module is not AOT and cannot be made AOT compatible.  This might change when Ivy comes but this is a limitation for now.  If you are not using the runtime feature then it should work with AOT.  If not let me know.

**Comment by kostenickj** [comment]
Ah, I was using the runtime feature. Good to know. Thanks .

**Comment by kostenickj** [comment]
I was wondering, will server side rendering every be supported? Is it planned?

**Comment by Hypercubed** [comment]
I've though about it... but not sure how it would work in this setup.  The markdown would need to pass through the remark parser twice.  Once for SSR then again on the client to support thinks like the run-time content.
